# https://www.postgresql.org/docs/current/ssl-tcp.html
# https://www.postgresql.org/docs/current/libpq-ssl.html
# psql "host=172.17.0.1 port=54321 user=postgres sslmode=verify-ca sslrootcert=./ssl/root.crt sslcert=./ssl/postgresql.crt sslkey=./ssl/postgresql.key"
volumes:
  postgres_data:
services:
  postgres:
    build: .
    restart: always
    environment:
      TZ: America/Sao_Paulo
      update: 1
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "psql -w -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1'"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "54321:5432"
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c ssl_ca_file=/var/lib/postgresql/root.crt
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./ssl/server.crt:/var/lib/postgresql/server.crt
      - ./ssl/server.key:/var/lib/postgresql/server.key
      - ./ssl/root.crt:/var/lib/postgresql/root.crt
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
